@startuml

skinparam monochrome true

interface ItemInterface {
    +string getName()
    +void printStructure(string actualPath)
}

interface LeafInterface {
    +string getName()
    +void printStructure(string actualPath)
}

interface BranchInterface {
    +string getName()
    +void printStructure(string actualPath)
    #ItemInterface[] getChildren()
}

class Leaf {
    -string name
    +string getName()
    +void printStructure(string actualPath)
}

class Branch {
    -ItemInterface[] children
    -string name
    +string getName()
    +void printStructure(string actualPath)
    #ItemInterface[] getChildren()

}

class Root {
    ItemInterface root
    +void printStructure()
}

class Client {
}

ItemInterface <|-- LeafInterface
ItemInterface <|-- BranchInterface
LeafInterface <|.. Leaf
BranchInterface <|.. Branch
ItemInterface "m" --* "1" Branch
ItemInterface "1" --* "1" Root
Root --o Client


@enduml
